Feedback from TSEs
shubhsk88/newyork-times-clone pull request #3
Opened 2020-03-30 20:59 UTC by shubhsk88

We built this website clone using Float, grid, and flex and used font-awesome for the icons.

2020-03-30 23:56 UTC, majovanilla requested changes
Hey team, 👋

## You did an *amazing*🌟 ✨ job on this project! 👊🏻  💯
You have met almost every requirement and your page looks very similar to the original one!!
There are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

- Improve your pull request messages. Check this [example](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
- Please implement the required changes on the commented code below :point_down: 

### Optional Changes:

If you want to make your project even better 🔥💥, I have a few suggestions you can implement.  

These are completely [Optional]: 🦔

- Your project would look sooo much better if you include the hover effects on the links of the page, like the original version.

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

2020-03-30 23:56 UTC, majovanilla commented on README.md
> +
- [ ]  Improve your Readme file. It should be descriptive of the project. You are using the correct template but now you need to fill it with information about your project. You can add details about what you did in this project, why you did it, how you did it...Check this [link](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) for more info.

2020-03-30 23:56 UTC, majovanilla commented on README.md
> +
- [ ] Add information about you! Include your LinkedIn, Twitter or other social media so people can contact you!

2020-03-30 23:56 UTC, majovanilla commented on index.html
> +            </div>
- [ ] The icons should also be links. :smile:

2020-03-30 23:56 UTC, majovanilla commented on index.html
> +          </ul>
- [ ] The articles' titles on the aside should also be links.

2020-03-30 23:56 UTC, majovanilla commented on index.html
> +            </div>
- [ ] The elements in this div should be links, too.

2020-03-30 23:56 UTC, majovanilla commented on index.html
> +                <img
- [ ] All the articles on this section should contain links on their titles.

2020-03-30 23:56 UTC, majovanilla commented on index.html
> +          </div>
- [ ] All the titles on this section should be links.

2020-04-01 00:31 UTC, addod19 commented
## Pull Request under review by Daniel Larbi Addo (TSE)

2020-04-01 00:48 UTC, addod19 approved these changes
## Status: Approved :trophy: :balloon:

Hi **TEAM**, congratulations on this great project 👍 You guys implemented all the requested changes pointed out by the previous TSE 😄 Awesome!!! The project is approved, go ahead and merge to master and submit a project completion form.
Before we merge let us add ```our emails``` to the author section of our README file and also let us update our live link to reflect our current changes 🙂 

Good luck with your next projects 👌 
_Happy coding_ 👨‍💻 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2020-04-01 14:39 UTC, merged